lsi: false
safe: true
source: /root
incremental: false
highlighter: rouge
title: Statistics Crash Course
description: When to use what
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
remote_theme: pages-themes/cayman@v0.2.0
plugins:
    - jekyll-remote-theme # add this line to the plugins list if you already have one
