lsi: false
safe: true
source: /root
incremental: false
highlighter: rouge
title: Statistics Crash Course: When to use What
description: Below are guidelines that should be followed to determine what sort of statistical test should be used for a particular type of dataset
theme: jekyll-theme-cayman
plugins:
    - jekyll-remote-theme # add this line to the plugins list if you already have one
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

